title: DAA Digi Government
author: Jolene Smith
email: joleneupdikesmith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  SAA Digi Government

twitter_username: aejolene
github_username:  aejolene

sass:
    style: compressed
theme: jekyll-theme-slate
